// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1WjsWwTOPuxrdt87BxriI9AwJElKn5Lo',
    appId: '1:468186522687:web:dbe9409efb220b6c24048a',
    messagingSenderId: '468186522687',
    projectId: 'bebek360-f7e7f',
    authDomain: 'bebek360-f7e7f.firebaseapp.com',
    storageBucket: 'bebek360-f7e7f.firebasestorage.app',
    measurementId: 'G-KG8D752QBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBWDv7qz6Y5V4KaFoYNCzBz5VNI6yGaYI',
    appId: '1:468186522687:android:1297cc8c93610d1724048a',
    messagingSenderId: '468186522687',
    projectId: 'bebek360-f7e7f',
    storageBucket: 'bebek360-f7e7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDlVKJ182xrmcbBobIzQepVuYQ5CMRCkk',
    appId: '1:468186522687:ios:23946abe1656278a24048a',
    messagingSenderId: '468186522687',
    projectId: 'bebek360-f7e7f',
    storageBucket: 'bebek360-f7e7f.firebasestorage.app',
    iosBundleId: 'com.example.bebek360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDlVKJ182xrmcbBobIzQepVuYQ5CMRCkk',
    appId: '1:468186522687:ios:23946abe1656278a24048a',
    messagingSenderId: '468186522687',
    projectId: 'bebek360-f7e7f',
    storageBucket: 'bebek360-f7e7f.firebasestorage.app',
    iosBundleId: 'com.example.bebek360',
  );

}